controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

joint_trajectory_controller:
  ros__parameters:
    joints: [j1, j2, j3, j4, j5, j6]
    command_interfaces: [position]
    state_interfaces: [position, velocity]

    constraints:
      stopped_velocity_tolerance: 0.2
      goal_time: 2.0
      j1: {trajectory: 0.5, goal: 0.2}
      j2: {trajectory: 0.5, goal: 0.2}
      j3: {trajectory: 0.5, goal: 0.2}
      j4: {trajectory: 0.5, goal: 0.2}
      j5: {trajectory: 0.5, goal: 0.2}
      j6: {trajectory: 0.5, goal: 0.2}

